services:
  flask-app:
    build: .
    container_name: flask-devops-app
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=Production
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
